name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  deploy:
    name: 🛠📤 Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Create env file
        run: |
          touch .env
          echo API_BASE_URL=${{ secrets.API_BASE_URL }} >> .env
      - name: Setup node
        uses: actions/setup-node@master
        with:
          cache: 'npm'
      - name: Build dist folder
        run: |
          npm install
          npm run generate
          npm run build
      - name: Copy dist folder to production
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: ${{ secrets.APP_PATH }}
