name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    name: 🛠 Build artifact
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - run: |
            touch .env
            echo API_BASE_URL=${{ secrets.API_BASE_URL }} >> .env
        - uses: actions/setup-node@master
          with:
            cache: 'npm'
        - run: npm install
        - run: npm run generate
        - run: npm run build

  deploy:
    name: 📤 Deploy to production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist"
          target: ${{ secrets.APP_PATH }}
